"""Initialzing Database

Revision ID: 8b4cf92189ac
Revises: 
Create Date: 2024-10-18 19:56:07.940526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4cf92189ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('department', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('unit_in_church', sa.String(length=40), nullable=True),
    sa.Column('first_time', sa.Boolean(), nullable=True),
    sa.Column('member', sa.Boolean(), nullable=True),
    sa.Column('level', sa.Enum('LEVEL_100', 'LEVEL_200', 'LEVEL_300', 'LEVEL_400', 'LEVEL_500', name='level'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendee')
    # ### end Alembic commands ###
